# Generated by Django 3.0.4 on 2020-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gcreds',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
