# Generated by Django 3.0.4 on 2020-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_profile_gcreds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='playlistid',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
