# Generated by Django 3.0.4 on 2020-03-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_auto_20200326_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yttrack',
            name='vidid',
            field=models.CharField(default='example', max_length=99),
            preserve_default=False,
        ),
    ]
