# Generated by Django 3.0.4 on 2020-03-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_auto_20200326_1708'),
        ('spot', '0003_profile_playlistid'),
    ]

    operations = [
    ]
