# Generated by Django 3.0.4 on 2020-03-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0007_profile_ytid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='playlistid',
        ),
    ]
