# Generated by Django 3.0.4 on 2020-03-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0008_remove_profile_playlistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='yttrack',
            name='spid',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='yttrack',
            name='vidid',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
