# Generated by Django 3.0.4 on 2020-03-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0009_auto_20200328_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gcreds',
        ),
    ]
