# Generated by Django 3.0.4 on 2020-04-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0010_remove_profile_gcreds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='spid',
            new_name='curr_sp_playlistid',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ytid',
            new_name='curr_yt_playlistid',
        ),
        migrations.RenameField(
            model_name='yttrack',
            old_name='spid',
            new_name='sp_playlistid',
        ),
    ]
